site_name: Rice Price Collector
repo_url: https://github.com/ChamoChiran/rice_price_collector
repo_name: GitHub

# Theme customization
theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  generator: false  # Remove 'Made with Material for MkDocs' footer

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md

  - Downloader:
      - Overview: downloader/index.md
      - Configuration: downloader/config.md
      - PDF Downloader: downloader/downloader.md

  - Parser:
      - Overview: parser/index.md
      - Batch Extractor: parser/batch_extract.md
      - Rice Extractor: parser/extractors/rice.md
      - Columns: parser/columns.md
      - Utilities: parser/utils.md
      - Configuration: parser/config.md

  - API Reference:
      - Downloader Module: api/downloader.md
      - Parser Module: api/parser.md

  - About: about.md
